app:
  host: plark.io
  port: 80
  secure: true
  useCache: true
  isTest: true

  gtmKey: 'GTM-K8BVBNG'

  mailchimpApiKey: false
  mailchimpListID: false

  telegramBotToken: false
  telegramChatID: false
